---
- name: Install EPEL repo
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Disable EPEL repo
  community.general.files.ini_file:
    path: "/etc/yum.repos.d/epel.repo"
    section: epel
    option: enabled
    value: "{{ epel_disable | ternary(0, 1) }}"
    mode: 0644
