---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether EPEL installed
      ansible.builtin.command: yum repolist enabled  # noqa command-instead-of-module
      register: epel_installed
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Make sure EPEL is installed
      ansible.builtin.debug:
        var: epel_installed

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
